locales:
  dag:
    name: Dagbani Keyboards
    description: >-
      Mobile OS keyboards for the Dagbani language from the Divvun group
      at UiT.
  en:
    name: Dagbani Keyboards
    description: >-
      Mobile OS keyboards for the Dagbani language from the Divvun group
      at UiT.
  nb:
    name: Dagbani tastatur
    description: Mobiltastatur for Dagbani fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
